/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JPanel;

/**
 *
 * @author slix0
 */
public class Vista_InicioProceso extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_InicioProceso
     */
    public Vista_InicioProceso() {
        initComponents();
    }

    public JPanel getPnAnamesis() {
        return pnAnamesis;
    }

    public void setPnAnamesis(JPanel pnAnamesis) {
        this.pnAnamesis = pnAnamesis;
    }

    public JPanel getPnCitas() {
        return pnCitas;
    }

    public void setPnCitas(JPanel pnCitas) {
        this.pnCitas = pnCitas;
    }

   

    public JPanel getPnFacturacion() {
        return pnFacturacion;
    }

    public void setPnFacturacion(JPanel pnFacturacion) {
        this.pnFacturacion = pnFacturacion;
    }

    public JPanel getPnHistorial() {
        return pnHistorial;
    }

    public void setPnHistorial(JPanel pnHistorial) {
        this.pnHistorial = pnHistorial;
    }

    public JPanel getPnHistorialClinico() {
        return pnHistorialClinico;
    }

    public void setPnHistorialClinico(JPanel pnHistorialClinico) {
        this.pnHistorialClinico = pnHistorialClinico;
    }

    public JPanel getPnListadoPac() {
        return pnListadoPac;
    }

    public void setPnListadoPac(JPanel pnListadoPac) {
        this.pnListadoPac = pnListadoPac;
    }

    public JPanel getPnreceta() {
        return pnreceta;
    }

    public void setPnreceta(JPanel pnreceta) {
        this.pnreceta = pnreceta;
    }

    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnListadoPac = new javax.swing.JPanel();
        pnAnamesis = new javax.swing.JPanel();
        pnHistorial = new javax.swing.JPanel();
        pnHistorialClinico = new javax.swing.JPanel();
        pnCitas = new javax.swing.JPanel();
        pnreceta = new javax.swing.JPanel();
        pnFacturacion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        pnListadoPac.setBackground(new java.awt.Color(255, 255, 255));
        pnListadoPac.setPreferredSize(new java.awt.Dimension(1255, 752));

        javax.swing.GroupLayout pnListadoPacLayout = new javax.swing.GroupLayout(pnListadoPac);
        pnListadoPac.setLayout(pnListadoPacLayout);
        pnListadoPacLayout.setHorizontalGroup(
            pnListadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1255, Short.MAX_VALUE)
        );
        pnListadoPacLayout.setVerticalGroup(
            pnListadoPacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("LISTADO DE PACIENTES", pnListadoPac);

        pnAnamesis.setBackground(new java.awt.Color(255, 255, 255));
        pnAnamesis.setPreferredSize(new java.awt.Dimension(1255, 752));

        javax.swing.GroupLayout pnAnamesisLayout = new javax.swing.GroupLayout(pnAnamesis);
        pnAnamesis.setLayout(pnAnamesisLayout);
        pnAnamesisLayout.setHorizontalGroup(
            pnAnamesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1255, Short.MAX_VALUE)
        );
        pnAnamesisLayout.setVerticalGroup(
            pnAnamesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ANAMNESIS", pnAnamesis);

        pnHistorial.setBackground(new java.awt.Color(255, 255, 255));
        pnHistorial.setPreferredSize(new java.awt.Dimension(1255, 752));

        javax.swing.GroupLayout pnHistorialLayout = new javax.swing.GroupLayout(pnHistorial);
        pnHistorial.setLayout(pnHistorialLayout);
        pnHistorialLayout.setHorizontalGroup(
            pnHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1255, Short.MAX_VALUE)
        );
        pnHistorialLayout.setVerticalGroup(
            pnHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("HISTORIAL MEDICO", pnHistorial);

        pnHistorialClinico.setBackground(new java.awt.Color(255, 255, 255));
        pnHistorialClinico.setPreferredSize(new java.awt.Dimension(1255, 752));

        javax.swing.GroupLayout pnHistorialClinicoLayout = new javax.swing.GroupLayout(pnHistorialClinico);
        pnHistorialClinico.setLayout(pnHistorialClinicoLayout);
        pnHistorialClinicoLayout.setHorizontalGroup(
            pnHistorialClinicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1255, Short.MAX_VALUE)
        );
        pnHistorialClinicoLayout.setVerticalGroup(
            pnHistorialClinicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("HISTORIAL CLINICO", pnHistorialClinico);

        pnCitas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnCitasLayout = new javax.swing.GroupLayout(pnCitas);
        pnCitas.setLayout(pnCitasLayout);
        pnCitasLayout.setHorizontalGroup(
            pnCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1255, Short.MAX_VALUE)
        );
        pnCitasLayout.setVerticalGroup(
            pnCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("AGENDA DE CITAS", pnCitas);

        pnreceta.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnrecetaLayout = new javax.swing.GroupLayout(pnreceta);
        pnreceta.setLayout(pnrecetaLayout);
        pnrecetaLayout.setHorizontalGroup(
            pnrecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1255, Short.MAX_VALUE)
        );
        pnrecetaLayout.setVerticalGroup(
            pnrecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("RECETA", pnreceta);

        pnFacturacion.setBackground(new java.awt.Color(255, 255, 255));
        pnFacturacion.setPreferredSize(new java.awt.Dimension(1255, 752));

        javax.swing.GroupLayout pnFacturacionLayout = new javax.swing.GroupLayout(pnFacturacion);
        pnFacturacion.setLayout(pnFacturacionLayout);
        pnFacturacionLayout.setHorizontalGroup(
            pnFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1255, Short.MAX_VALUE)
        );
        pnFacturacionLayout.setVerticalGroup(
            pnFacturacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("FACTURACION", pnFacturacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1259, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnAnamesis;
    private javax.swing.JPanel pnCitas;
    private javax.swing.JPanel pnFacturacion;
    private javax.swing.JPanel pnHistorial;
    private javax.swing.JPanel pnHistorialClinico;
    private javax.swing.JPanel pnListadoPac;
    private javax.swing.JPanel pnreceta;
    // End of variables declaration//GEN-END:variables
}
