package View;

import com.toedter.calendar.JDateChooser;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import jtextfieldround.JTextFieldRound;
import org.edisoncor.gui.button.ButtonRound;
import org.edisoncor.gui.panel.PanelNice;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author slix0
 */
public class Vista_Receta extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Anamesis
     */
    public Vista_Receta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogFarmaco = new javax.swing.JDialog();
        paneldialog = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblcie10 = new javax.swing.JTable();
        txtbuscarfar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dialogCIE = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        txtbuscarcie10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbldoctor1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        btncerrar = new org.edisoncor.gui.button.ButtonRound();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jdcFechareceta = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIDreceta = new jtextfieldround.JTextFieldRound();
        txtBuscarFarmaco = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReceta = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtIdfamaco = new jtextfieldround.JTextFieldRound();
        txtCie = new jtextfieldround.JTextFieldRound();
        jLabel6 = new javax.swing.JLabel();
        btnBuscarcie = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        txtdosis = new jtextfieldround.JTextFieldRound();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtdosis1 = new jtextfieldround.JTextFieldRound();
        jButton1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCrearRec = new javax.swing.JButton();
        btnEditarrec = new javax.swing.JButton();
        btnEliminarrec = new javax.swing.JButton();

        paneldialog.setBackground(new java.awt.Color(90, 166, 166));

        tblcie10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "MILIGRAMOS"
            }
        ));
        jScrollPane3.setViewportView(tblcie10);
        if (tblcie10.getColumnModel().getColumnCount() > 0) {
            tblcie10.getColumnModel().getColumn(0).setHeaderValue("Cedula");
            tblcie10.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            tblcie10.getColumnModel().getColumn(2).setHeaderValue("Apellido");
            tblcie10.getColumnModel().getColumn(3).setHeaderValue("Especialidad");
            tblcie10.getColumnModel().getColumn(4).setHeaderValue("Telefono");
        }

        txtbuscarfar.setToolTipText("Ingrese la cedula o el nombre para buscar");

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Buscar:");

        javax.swing.GroupLayout paneldialogLayout = new javax.swing.GroupLayout(paneldialog);
        paneldialog.setLayout(paneldialogLayout);
        paneldialogLayout.setHorizontalGroup(
            paneldialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneldialogLayout.createSequentialGroup()
                .addGroup(paneldialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneldialogLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbuscarfar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneldialogLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        paneldialogLayout.setVerticalGroup(
            paneldialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneldialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(paneldialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscarfar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogFarmacoLayout = new javax.swing.GroupLayout(dialogFarmaco.getContentPane());
        dialogFarmaco.getContentPane().setLayout(dialogFarmacoLayout);
        dialogFarmacoLayout.setHorizontalGroup(
            dialogFarmacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneldialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogFarmacoLayout.setVerticalGroup(
            dialogFarmacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneldialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(166, 104, 216));

        txtbuscarcie10.setToolTipText("Ingrese la cedula o el nombre para buscar");

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Buscar:");

        tbldoctor1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "PATOLOGIA"
            }
        ));
        jScrollPane7.setViewportView(tbldoctor1);
        if (tbldoctor1.getColumnModel().getColumnCount() > 0) {
            tbldoctor1.getColumnModel().getColumn(0).setHeaderValue("Cedula");
            tbldoctor1.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            tbldoctor1.getColumnModel().getColumn(2).setHeaderValue("Apellido");
            tbldoctor1.getColumnModel().getColumn(3).setHeaderValue("Especialidad");
            tbldoctor1.getColumnModel().getColumn(4).setHeaderValue("Telefono");
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbuscarcie10, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscarcie10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(288, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout dialogCIELayout = new javax.swing.GroupLayout(dialogCIE.getContentPane());
        dialogCIE.getContentPane().setLayout(dialogCIELayout);
        dialogCIELayout.setHorizontalGroup(
            dialogCIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogCIELayout.setVerticalGroup(
            dialogCIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 690));

        panelNice1.setBackground(new java.awt.Color(166, 104, 216));
        panelNice1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncerrar.setBackground(new java.awt.Color(166, 104, 216));
        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });
        panelNice1.add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/imgReceta.jpg"))); // NOI18N
        panelNice1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 250, 110));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Daniela San Martín");
        panelNice1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel21.setBackground(new java.awt.Color(0, 153, 153));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 255, 255));
        jLabel21.setText("ODONTOLOGA");
        panelNice1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelNice1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 530, 10));
        panelNice1.add(jdcFechareceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 160, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Luis Moscoso 7 y Ricardo Marquez       Celular: 0989726783         Cuenca-Ecuador");
        panelNice1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Observaciones:");
        panelNice1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 110, 20));
        panelNice1.add(txtIDreceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 100, 21));

        txtBuscarFarmaco.setText("Buscar");
        panelNice1.add(txtBuscarFarmaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        tblReceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DETALLE", "CANTIDAD", "DOSIS", "FRECUENCIA"
            }
        ));
        jScrollPane1.setViewportView(tblReceta);

        panelNice1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 770, 140));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha:");
        panelNice1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 20));
        panelNice1.add(txtIdfamaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 150, 21));
        panelNice1.add(txtCie, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 360, 21));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CIE-10:");
        panelNice1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 70, 20));

        btnBuscarcie.setText("Buscar");
        panelNice1.add(btnBuscarcie, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, -1, -1));
        panelNice1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 70, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Farmaco:");
        panelNice1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        panelNice1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 390, 130));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Cantidad:");
        panelNice1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 70, 20));
        panelNice1.add(txtdosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, 150, 21));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Frecuencia:");
        panelNice1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 80, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Dosis:");
        panelNice1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 70, 20));
        panelNice1.add(txtdosis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 150, 21));

        jButton1.setText("Agregar");
        panelNice1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 240, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Alergias:");
        panelNice1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 80, 20));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        panelNice1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 420, 130));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO CIE-10", "TITULO CIE-10", "CATEGORIA"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        panelNice1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 280, 330, 140));

        jPanel1.add(panelNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1150, 600));

        btnCrearRec.setText("Crear");
        jPanel1.add(btnCrearRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 160, 40));

        btnEditarrec.setText("Editar");
        jPanel1.add(btnEditarrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 620, 160, 40));

        btnEliminarrec.setText("Eliminar");
        jPanel1.add(btnEliminarrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrarActionPerformed

    public JButton getBtnBuscarcie() {
        return btnBuscarcie;
    }

    public void setBtnBuscarcie(JButton btnBuscarcie) {
        this.btnBuscarcie = btnBuscarcie;
    }

    public JButton getBtnCrearRec() {
        return btnCrearRec;
    }

    public void setBtnCrearRec(JButton btnCrearRec) {
        this.btnCrearRec = btnCrearRec;
    }

    public JButton getBtnEditarrec() {
        return btnEditarrec;
    }

    public void setBtnEditarrec(JButton btnEditarrec) {
        this.btnEditarrec = btnEditarrec;
    }

    public JButton getBtnEliminarrec() {
        return btnEliminarrec;
    }

    public void setBtnEliminarrec(JButton btnEliminarrec) {
        this.btnEliminarrec = btnEliminarrec;
    }

    public ButtonRound getBtncerrar() {
        return btncerrar;
    }

    public void setBtncerrar(ButtonRound btncerrar) {
        this.btncerrar = btncerrar;
    }

    public JDialog getDialogbuscar() {
        return dialogFarmaco;
    }

    public void setDialogbuscar(JDialog dialogbuscar) {
        this.dialogFarmaco = dialogbuscar;
    }

    public JDialog getDialogpac() {
        return dialogCIE;
    }

    public void setDialogpac(JDialog dialogpac) {
        this.dialogCIE = dialogpac;
    }

    public JDateChooser getJdcFechareceta() {
        return jdcFechareceta;
    }

    public void setJdcFechareceta(JDateChooser jdcFechareceta) {
        this.jdcFechareceta = jdcFechareceta;
    }

    public JDateChooser getJdcFechareceta2() {
        return jdcFechareceta2;
    }

    public void setJdcFechareceta2(JDateChooser jdcFechareceta2) {
        this.jdcFechareceta2 = jdcFechareceta2;
    }

    public PanelNice getPanelNice1() {
        return panelNice1;
    }

    public void setPanelNice1(PanelNice panelNice1) {
        this.panelNice1 = panelNice1;
    }

    public PanelNice getPanelNice2() {
        return panelNice2;
    }

    public void setPanelNice2(PanelNice panelNice2) {
        this.panelNice2 = panelNice2;
    }

    public JPanel getPaneldialog() {
        return paneldialog;
    }

    public void setPaneldialog(JPanel paneldialog) {
        this.paneldialog = paneldialog;
    }

    public JTable getTblReceta() {
        return tblReceta;
    }

    public void setTblReceta(JTable tblReceta) {
        this.tblReceta = tblReceta;
    }

    public JTable getTblReceta2() {
        return tblReceta2;
    }

    public void setTblReceta2(JTable tblReceta2) {
        this.tblReceta2 = tblReceta2;
    }

    public JTable getTbldoctor() {
        return tblcie10;
    }

    public void setTbldoctor(JTable tbldoctor) {
        this.tblcie10 = tbldoctor;
    }

    public JButton getTxtBuscarFarmaco() {
        return txtBuscarFarmaco;
    }

    public void setTxtBuscarFarmaco(JButton txtBuscarFarmaco) {
        this.txtBuscarFarmaco = txtBuscarFarmaco;
    }

    public JTextFieldRound getTxtCie() {
        return txtCie;
    }

    public void setTxtCie(JTextFieldRound txtCie) {
        this.txtCie = txtCie;
    }

    public JTextFieldRound getTxtCie2() {
        return txtCie2;
    }

    public void setTxtCie2(JTextFieldRound txtCie2) {
        this.txtCie2 = txtCie2;
    }

    public JTextFieldRound getTxtIDreceta() {
        return txtIDreceta;
    }

    public void setTxtIDreceta(JTextFieldRound txtIDreceta) {
        this.txtIDreceta = txtIDreceta;
    }

    public JTextFieldRound getTxtIDreceta2() {
        return txtIDreceta2;
    }

    public void setTxtIDreceta2(JTextFieldRound txtIDreceta2) {
        this.txtIDreceta2 = txtIDreceta2;
    }

    public JTextFieldRound getTxtIdfamaco() {
        return txtIdfamaco;
    }

    public void setTxtIdfamaco(JTextFieldRound txtIdfamaco) {
        this.txtIdfamaco = txtIdfamaco;
    }

    public JTextFieldRound getTxtIdfamaco2() {
        return txtIdfamaco2;
    }

    public void setTxtIdfamaco2(JTextFieldRound txtIdfamaco2) {
        this.txtIdfamaco2 = txtIdfamaco2;
    }

    public JTextArea getTxtIndicaciones() {
        return txtIndicaciones;
    }

    public void setTxtIndicaciones(JTextArea txtIndicaciones) {
        this.txtIndicaciones = txtIndicaciones;
    }

    public JTextArea getTxtIndicaciones2() {
        return txtIndicaciones2;
    }

    public void setTxtIndicaciones2(JTextArea txtIndicaciones2) {
        this.txtIndicaciones2 = txtIndicaciones2;
    }

    public JTextField getTxtbuscardoc() {
        return txtbuscarfar;
    }

    public void setTxtbuscardoc(JTextField txtbuscardoc) {
        this.txtbuscarfar = txtbuscardoc;
    }

    public JTextField getTxtbuscarpac() {
        return txtbuscarcie10;
    }

    public void setTxtbuscarpac(JTextField txtbuscarpac) {
        this.txtbuscarcie10 = txtbuscarpac;
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarcie;
    private javax.swing.JButton btnCrearRec;
    private javax.swing.JButton btnEditarrec;
    private javax.swing.JButton btnEliminarrec;
    private org.edisoncor.gui.button.ButtonRound btncerrar;
    private javax.swing.JDialog dialogCIE;
    private javax.swing.JDialog dialogFarmaco;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    public static com.toedter.calendar.JDateChooser jdcFechareceta;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private javax.swing.JPanel paneldialog;
    private javax.swing.JTable tblReceta;
    private javax.swing.JTable tblcie10;
    private javax.swing.JTable tbldoctor1;
    private javax.swing.JButton txtBuscarFarmaco;
    private jtextfieldround.JTextFieldRound txtCie;
    private jtextfieldround.JTextFieldRound txtIDreceta;
    private jtextfieldround.JTextFieldRound txtIdfamaco;
    private javax.swing.JTextField txtbuscarcie10;
    private javax.swing.JTextField txtbuscarfar;
    private jtextfieldround.JTextFieldRound txtdosis;
    private jtextfieldround.JTextFieldRound txtdosis1;
    // End of variables declaration//GEN-END:variables
}
