/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Persona;
import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import jtextfieldround.JTextFieldRound;

public class Vista_Citas_Tratamiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Citas_Tratamiento
     */
    public Vista_Citas_Tratamiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgendar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNombredoc = new jtextfieldround.JTextFieldRound();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jdateFecha = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jareades = new javax.swing.JTextArea();
        txtficha = new jtextfieldround.JTextFieldRound();
        txtApellidosPac = new jtextfieldround.JTextFieldRound();
        btnAgendar1 = new javax.swing.JButton();
        btnAgendar2 = new javax.swing.JButton();
        txthora = new jtextfieldround.JTextFieldRound();
        cboscedulapac = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNombrePac = new jtextfieldround.JTextFieldRound();
        cbosceduladoc = new javax.swing.JComboBox<>();
        panelNice2 = new org.edisoncor.gui.panel.PanelNice();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblcitas = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNice1.setBackground(new java.awt.Color(166, 104, 216));
        panelNice1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CEDULA DEL PACIENTE:");
        panelNice1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FICHA:");
        panelNice1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 20));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("APELLIDOS DEL PACIENTE:");
        panelNice1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        btnAgendar.setText("ELIMINAR");
        panelNice1.add(btnAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 130, 40));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NOMBRE DEL DOCTOR:");
        panelNice1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));
        panelNice1.add(txtNombredoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 220, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CEDULA DEL DOCTOR:");
        panelNice1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("FECHA:");
        panelNice1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        panelNice1.add(jdateFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 220, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("HORA:");
        panelNice1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DESCRIPCION:");
        panelNice1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jareades.setColumns(20);
        jareades.setRows(5);
        jScrollPane2.setViewportView(jareades);

        panelNice1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 270, 160));
        panelNice1.add(txtficha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, 20));
        panelNice1.add(txtApellidosPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 220, 20));

        btnAgendar1.setText("AGENDAR");
        panelNice1.add(btnAgendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 120, 40));

        btnAgendar2.setText("ACTUALIZAR");
        panelNice1.add(btnAgendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, 40));
        panelNice1.add(txthora, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 220, 20));

        cboscedulapac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sleccionar", "Item 2", "Item 3", "Item 4" }));
        panelNice1.add(cboscedulapac, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 200, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMBRES DEL PACIENTE:");
        panelNice1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));
        panelNice1.add(txtNombrePac, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 220, 20));

        panelNice1.add(cbosceduladoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 220, -1));

        jPanel2.add(panelNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 480, 490));

        panelNice2.setBackground(new java.awt.Color(90, 166, 166));
        panelNice2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblcitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblcitas);

        panelNice2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 600, 560));

        jPanel2.add(panelNice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 630, 600));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/LOGO DENTAL daniela san martin -1_opt (2).png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 380, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1193, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnAgendar1;
    private javax.swing.JButton btnAgendar2;
    private javax.swing.JComboBox<Persona> cbosceduladoc;
    private javax.swing.JComboBox<String> cboscedulapac;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jareades;
    private com.toedter.calendar.JDateChooser jdateFecha;
    private javax.swing.JTable jtblcitas;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private org.edisoncor.gui.panel.PanelNice panelNice2;
    private jtextfieldround.JTextFieldRound txtApellidosPac;
    private jtextfieldround.JTextFieldRound txtNombrePac;
    private jtextfieldround.JTextFieldRound txtNombredoc;
    private jtextfieldround.JTextFieldRound txtficha;
    private jtextfieldround.JTextFieldRound txthora;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCbosnombre() {
        return cboscedulapac;
    }

    public void setCbosnombre(JComboBox<String> cbosnombre) {
        this.cboscedulapac = cbosnombre;
    }

    public JTextFieldRound getTxtApellidosPac() {
        return txtApellidosPac;
    }

    public void setTxtApellidosPac(JTextFieldRound txtApellidosPac) {
        this.txtApellidosPac = txtApellidosPac;
    }


    public JTextFieldRound getTxtNombredoc() {
        return txtNombredoc;
    }

    public void setTxtNombredoc(JTextFieldRound txtNombredoc) {
        this.txtNombredoc = txtNombredoc;
    }

    public JTextFieldRound getTxtficha() {
        return txtficha;
    }

    public void setTxtficha(JTextFieldRound txtficha) {
        this.txtficha = txtficha;
    }

    public JTextFieldRound getTxthora() {
        return txthora;
    }

    public void setTxthora(JTextFieldRound txthora) {
        this.txthora = txthora;
    }

    public JTextArea getJareades() {
        return jareades;
    }

    public void setJareades(JTextArea jareades) {
        this.jareades = jareades;
    }

    public JDateChooser getJdateFecha() {
        return jdateFecha;
    }

    public void setJdateFecha(JDateChooser jdateFecha) {
        this.jdateFecha = jdateFecha;
    }

    public JTable getJtblcitas() {
        return jtblcitas;
    }

    public void setJtblcitas(JTable jtblcitas) {
        this.jtblcitas = jtblcitas;
    }

    public JButton getBtnAgendar1() {
        return btnAgendar1;
    }

    public void setBtnAgendar1(JButton btnAgendar1) {
        this.btnAgendar1 = btnAgendar1;
    }

    public JComboBox<Persona> getCbosceduladoc() {
        return cbosceduladoc;
    }

    public void setCbosceduladoc(JComboBox<Persona> cbosceduladoc) {
        this.cbosceduladoc = cbosceduladoc;
    }

    

    public JComboBox<String> getCboscedulapac() {
        return cboscedulapac;
    }

    public void setCboscedulapac(JComboBox<String> cboscedulapac) {
        this.cboscedulapac = cboscedulapac;
    }





}
