/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author slix0
 */
public class Vista_Rep_HistorialOdontologico extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Rep_HistorialOdontologico
     */
    public Vista_Rep_HistorialOdontologico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNice2 = new org.edisoncor.gui.panel.PanelNice();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        txtenfermedad = new jtextfieldround.JTextFieldRound();
        jLabel16 = new javax.swing.JLabel();
        txtantecedentes = new jtextfieldround.JTextFieldRound();
        jLabel18 = new javax.swing.JLabel();
        txttratamiento = new jtextfieldround.JTextFieldRound();
        jLabel19 = new javax.swing.JLabel();
        txtalergia = new jtextfieldround.JTextFieldRound();
        jLabel20 = new javax.swing.JLabel();
        txtmedicamento = new jtextfieldround.JTextFieldRound();
        jLabel21 = new javax.swing.JLabel();
        txtfumbebe = new jtextfieldround.JTextFieldRound();
        jLabel22 = new javax.swing.JLabel();
        txtproblemascar = new jtextfieldround.JTextFieldRound();
        jLabel23 = new javax.swing.JLabel();
        txtulcera = new jtextfieldround.JTextFieldRound();
        jLabel24 = new javax.swing.JLabel();
        txtpresion = new jtextfieldround.JTextFieldRound();
        jLabel25 = new javax.swing.JLabel();
        txthepatitis = new jtextfieldround.JTextFieldRound();
        jLabel26 = new javax.swing.JLabel();
        txtdiabetes = new jtextfieldround.JTextFieldRound();
        jLabel27 = new javax.swing.JLabel();
        txtepilepsia = new jtextfieldround.JTextFieldRound();
        jLabel29 = new javax.swing.JLabel();
        txtdolorescab = new jtextfieldround.JTextFieldRound();
        jLabel28 = new javax.swing.JLabel();
        txtaltend = new jtextfieldround.JTextFieldRound();
        jLabel30 = new javax.swing.JLabel();
        txtvih = new jtextfieldround.JTextFieldRound();
        jLabel39 = new javax.swing.JLabel();
        txtprobcoag = new jtextfieldround.JTextFieldRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelNice2.setBackground(new java.awt.Color(90, 166, 166));
        panelNice2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reporte Historial Medico");
        panelNice2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jButton1.setText("Imprimir");
        panelNice2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 570, 50));

        jLabel32.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Enfermedad Actual:");
        panelNice2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));
        panelNice2.add(txtenfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 310, 21));

        jLabel16.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Antecedentes familiares:");
        panelNice2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));
        panelNice2.add(txtantecedentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 310, 21));

        jLabel18.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tratamiento medico:");
        panelNice2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        panelNice2.add(txttratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 310, 21));

        jLabel19.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Alergia Medicamentos:");
        panelNice2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));
        panelNice2.add(txtalergia, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 370, 21));

        jLabel20.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Medicamentos Habituales: ");
        panelNice2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));
        panelNice2.add(txtmedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 370, 21));

        jLabel21.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Fuma o Bebe:");
        panelNice2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));
        panelNice2.add(txtfumbebe, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 370, 21));

        jLabel22.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Problemas Cardiacos:");
        panelNice2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        panelNice2.add(txtproblemascar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 310, 21));

        jLabel23.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Ulcera Gastrica:");
        panelNice2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
        panelNice2.add(txtulcera, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 310, 21));

        jLabel24.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Presion:");
        panelNice2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));
        panelNice2.add(txtpresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 310, 21));

        jLabel25.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Hepatitis:");
        panelNice2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        panelNice2.add(txthepatitis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 310, 21));

        jLabel26.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Diabetes:");
        panelNice2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, -1));
        panelNice2.add(txtdiabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 370, 21));

        jLabel27.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Epilepsia:");
        panelNice2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));
        panelNice2.add(txtepilepsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 370, 21));

        jLabel29.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Dolores de cabeza:");
        panelNice2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));
        panelNice2.add(txtdolorescab, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 370, 21));

        jLabel28.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Alteracion Endocrina:");
        panelNice2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));
        panelNice2.add(txtaltend, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 370, 21));

        jLabel30.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("VIH:");
        panelNice2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));
        panelNice2.add(txtvih, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 370, 21));

        jLabel39.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Problemas Coagulacion:");
        panelNice2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));
        panelNice2.add(txtprobcoag, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 310, 21));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelNice2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 320, 1020, 230));

        jButton2.setText("Cargar Datos");
        panelNice2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelNice2, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelNice2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.edisoncor.gui.panel.PanelNice panelNice2;
    private jtextfieldround.JTextFieldRound txtalergia;
    private jtextfieldround.JTextFieldRound txtaltend;
    private jtextfieldround.JTextFieldRound txtantecedentes;
    private jtextfieldround.JTextFieldRound txtdiabetes;
    private jtextfieldround.JTextFieldRound txtdolorescab;
    private jtextfieldround.JTextFieldRound txtenfermedad;
    private jtextfieldround.JTextFieldRound txtepilepsia;
    private jtextfieldround.JTextFieldRound txtfumbebe;
    private jtextfieldround.JTextFieldRound txthepatitis;
    private jtextfieldround.JTextFieldRound txtmedicamento;
    private jtextfieldround.JTextFieldRound txtpresion;
    private jtextfieldround.JTextFieldRound txtprobcoag;
    private jtextfieldround.JTextFieldRound txtproblemascar;
    private jtextfieldround.JTextFieldRound txttratamiento;
    private jtextfieldround.JTextFieldRound txtulcera;
    private jtextfieldround.JTextFieldRound txtvih;
    // End of variables declaration//GEN-END:variables
}
