/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author slix0
 */
public class Vista_Crud_HistorialMedico extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Crud_HistorialMedico
     */
    public Vista_Crud_HistorialMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelNice1 = new org.edisoncor.gui.panel.PanelNice();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombresEsp = new jtextfieldround.JTextFieldRound();
        dateFechanacEsp = new com.toedter.calendar.JDateChooser();
        txtNombresEsp1 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp2 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp3 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp4 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp5 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp6 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp8 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp9 = new jtextfieldround.JTextFieldRound();
        jButton1 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        btnAnteriorEsp = new org.edisoncor.gui.button.ButtonRound();
        panelNice2 = new org.edisoncor.gui.panel.PanelNice();
        txtNombresEsp15 = new jtextfieldround.JTextFieldRound();
        jLabel19 = new javax.swing.JLabel();
        txtNombresEsp16 = new jtextfieldround.JTextFieldRound();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtNombresEsp14 = new jtextfieldround.JTextFieldRound();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombresEsp17 = new jtextfieldround.JTextFieldRound();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtNombresEsp18 = new jtextfieldround.JTextFieldRound();
        jLabel27 = new javax.swing.JLabel();
        txtNombresEsp19 = new jtextfieldround.JTextFieldRound();
        jLabel28 = new javax.swing.JLabel();
        txtNombresEsp20 = new jtextfieldround.JTextFieldRound();
        jLabel29 = new javax.swing.JLabel();
        txtNombresEsp21 = new jtextfieldround.JTextFieldRound();
        jLabel30 = new javax.swing.JLabel();
        txtNombresEsp22 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp23 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp24 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp25 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp27 = new jtextfieldround.JTextFieldRound();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtNombresEsp28 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp29 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp31 = new jtextfieldround.JTextFieldRound();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtNombresEsp30 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp32 = new jtextfieldround.JTextFieldRound();
        jLabel39 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtNombresEsp26 = new jtextfieldround.JTextFieldRound();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtNombresEsp34 = new jtextfieldround.JTextFieldRound();
        jLabel31 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombresEsp38 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp36 = new jtextfieldround.JTextFieldRound();
        txtNombresEsp7 = new jtextfieldround.JTextFieldRound();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNice1.setBackground(new java.awt.Color(166, 104, 216));
        panelNice1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOMBRES:");
        panelNice1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APELLIDOS:");
        panelNice1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CEDULA:");
        panelNice1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("GENERO:");
        panelNice1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DIRECCION:");
        panelNice1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TELEFONO:");
        panelNice1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CORREO:");
        panelNice1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PROVINCIA:");
        panelNice1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CIUDAD:");
        panelNice1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FECHA DE NACIMIENTO:");
        panelNice1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));
        panelNice1.add(txtNombresEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 220, 21));
        panelNice1.add(dateFechanacEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 200, -1));
        panelNice1.add(txtNombresEsp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 150, 21));
        panelNice1.add(txtNombresEsp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 220, 21));
        panelNice1.add(txtNombresEsp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 220, 21));
        panelNice1.add(txtNombresEsp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 220, 21));
        panelNice1.add(txtNombresEsp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 220, 21));
        panelNice1.add(txtNombresEsp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 220, 21));
        panelNice1.add(txtNombresEsp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 220, 21));
        panelNice1.add(txtNombresEsp9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 220, 21));

        jButton1.setText("Buscar");
        panelNice1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel41.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("DATOS DEL PACIENTE");
        panelNice1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        btnAnteriorEsp.setBackground(new java.awt.Color(166, 104, 216));
        btnAnteriorEsp.setText("cerrar");
        panelNice1.add(btnAnteriorEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel2.add(panelNice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 460));

        panelNice2.setBackground(new java.awt.Color(90, 166, 166));
        panelNice2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelNice2.add(txtNombresEsp15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 200, 21));

        jLabel19.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Alegia Medicamentos:");
        panelNice2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));
        panelNice2.add(txtNombresEsp16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 200, 21));

        jLabel22.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Problemas Cardiacos:");
        panelNice2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jLabel24.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Presion:");
        panelNice2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));
        panelNice2.add(txtNombresEsp14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 200, 21));

        jLabel23.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Ulcera Gastrica:");
        panelNice2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jLabel20.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Medicamentos Habituales: ");
        panelNice2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jLabel21.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Fuma o Bebe:");
        panelNice2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        jLabel15.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Oximetria");
        panelNice2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, -1, -1));
        panelNice2.add(txtNombresEsp17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 200, 21));

        jLabel25.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Hepatitis:");
        panelNice2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jLabel26.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Diabetes:");
        panelNice2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));
        panelNice2.add(txtNombresEsp18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 200, 21));

        jLabel27.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Epilepsia:");
        panelNice2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));
        panelNice2.add(txtNombresEsp19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 200, 21));

        jLabel28.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Alteracion Endocrina:");
        panelNice2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));
        panelNice2.add(txtNombresEsp20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 200, 21));

        jLabel29.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Dolores de cabeza:");
        panelNice2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));
        panelNice2.add(txtNombresEsp21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 200, 21));

        jLabel30.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("VIH:");
        panelNice2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));
        panelNice2.add(txtNombresEsp22, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 200, 21));
        panelNice2.add(txtNombresEsp23, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 110, 30));
        panelNice2.add(txtNombresEsp24, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 200, 21));
        panelNice2.add(txtNombresEsp25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 200, 21));
        panelNice2.add(txtNombresEsp27, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 200, 21));

        jLabel33.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Arterial");
        panelNice2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, -1, -1));

        jLabel34.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Frecuencia ");
        panelNice2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, -1, -1));

        jLabel35.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Temperatura");
        panelNice2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, -1, -1));

        jLabel37.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Presion");
        panelNice2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, -1, -1));
        panelNice2.add(txtNombresEsp28, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 200, 21));
        panelNice2.add(txtNombresEsp29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 110, 30));
        panelNice2.add(txtNombresEsp31, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 110, 30));

        jLabel36.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Frecuencia ");
        panelNice2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, -1, -1));

        jLabel38.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Respiratoria X MIN");
        panelNice2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, -1, -1));

        jLabel40.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Cardiaca x min");
        panelNice2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, -1, -1));
        panelNice2.add(txtNombresEsp30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 110, 30));
        panelNice2.add(txtNombresEsp32, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 110, 30));

        jLabel39.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Problemas Cuagulacion:");
        panelNice2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, -1, -1));

        jLabel13.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DATOS DEL HISTORIAL MEDICO");
        panelNice2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel32.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Enfermedad Actual:");
        panelNice2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));
        panelNice2.add(txtNombresEsp26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 200, 21));

        jLabel16.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Antecedentes familiares:");
        panelNice2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel18.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tratamiento medico:");
        panelNice2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelNice2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 10, 490));
        panelNice2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 720, 10));
        panelNice2.add(txtNombresEsp34, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 200, 21));

        jLabel31.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("MEDICO TRATANTE:");
        panelNice2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel42.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("DATOS DEL MEDICO TRATANTE");
        panelNice2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CEDULA:");
        panelNice2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        panelNice2.add(txtNombresEsp38, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 200, 21));
        panelNice2.add(txtNombresEsp36, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, 21));
        panelNice2.add(txtNombresEsp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 160, 21));

        jButton3.setText("Imprimir");
        panelNice2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, 130, -1));

        jButton4.setText("Guardar");
        panelNice2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 120, -1));

        jLabel47.setFont(new java.awt.Font("SF Pro Display", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("BUSCAR");
        panelNice2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        panelNice2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 170, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelNice2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 310, 330));

        jPanel2.add(panelNice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 720, 650));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/LOGO DENTAL daniela san martin -1_opt (2).png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 420, 190));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 690));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRound btnAnteriorEsp;
    private com.toedter.calendar.JDateChooser dateFechanacEsp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private org.edisoncor.gui.panel.PanelNice panelNice1;
    private org.edisoncor.gui.panel.PanelNice panelNice2;
    private jtextfieldround.JTextFieldRound txtNombresEsp;
    private jtextfieldround.JTextFieldRound txtNombresEsp1;
    private jtextfieldround.JTextFieldRound txtNombresEsp14;
    private jtextfieldround.JTextFieldRound txtNombresEsp15;
    private jtextfieldround.JTextFieldRound txtNombresEsp16;
    private jtextfieldround.JTextFieldRound txtNombresEsp17;
    private jtextfieldround.JTextFieldRound txtNombresEsp18;
    private jtextfieldround.JTextFieldRound txtNombresEsp19;
    private jtextfieldround.JTextFieldRound txtNombresEsp2;
    private jtextfieldround.JTextFieldRound txtNombresEsp20;
    private jtextfieldround.JTextFieldRound txtNombresEsp21;
    private jtextfieldround.JTextFieldRound txtNombresEsp22;
    private jtextfieldround.JTextFieldRound txtNombresEsp23;
    private jtextfieldround.JTextFieldRound txtNombresEsp24;
    private jtextfieldround.JTextFieldRound txtNombresEsp25;
    private jtextfieldround.JTextFieldRound txtNombresEsp26;
    private jtextfieldround.JTextFieldRound txtNombresEsp27;
    private jtextfieldround.JTextFieldRound txtNombresEsp28;
    private jtextfieldround.JTextFieldRound txtNombresEsp29;
    private jtextfieldround.JTextFieldRound txtNombresEsp3;
    private jtextfieldround.JTextFieldRound txtNombresEsp30;
    private jtextfieldround.JTextFieldRound txtNombresEsp31;
    private jtextfieldround.JTextFieldRound txtNombresEsp32;
    private jtextfieldround.JTextFieldRound txtNombresEsp34;
    private jtextfieldround.JTextFieldRound txtNombresEsp36;
    private jtextfieldround.JTextFieldRound txtNombresEsp38;
    private jtextfieldround.JTextFieldRound txtNombresEsp4;
    private jtextfieldround.JTextFieldRound txtNombresEsp5;
    private jtextfieldround.JTextFieldRound txtNombresEsp6;
    private jtextfieldround.JTextFieldRound txtNombresEsp7;
    private jtextfieldround.JTextFieldRound txtNombresEsp8;
    private jtextfieldround.JTextFieldRound txtNombresEsp9;
    // End of variables declaration//GEN-END:variables
}
